### ISSUE TITLE
Effect cleanup

### ISSUE THREAD

**Issue by davidkpiano** [davidkpiano/useEffectReducer#1]
Thinking out loud: we need some way to control the cleanup of effects. Right now, `useEffectReducer` treats effects as fire-and-forget, which is fine for many use-cases, but can introduce memory leaks or undesired behaviors for certain effects that are supposed to have a specific lifetime.

One solution: `exec(effect)` can return an entity which can be explicitly managed in the reducer state:

```js
const someReducer = (state, event, exec) => {
  if (event.type === 'FETCH') {
    return {
      // ...
      effect: exec({ type: 'fetch', user: 'David' })
    }
  else if (event.type === 'CANCEL') {
    // stop effect
    state.effect.stop();

    return {/* ... */}
  }
}
```

The `effect` returned from `exec(...)` will be an opaque object that (for now) just has a unique `id` and a `.stop()` method. This will call the disposal function returned from the effect:

```js
const [state, dispatch] = useEffectReducer(someReducer, initialState, {
  fetch: () => {
    // ...

    return () => {
      // cancel fetch request
    }
  }
});
```

**Comment by luisgurmendezMLabs** [comment]
I don't personally like having fn in the state. Thinking out load it would be great to have this done by  dispatching a cleanup so that you could keep the flux pattern

**Comment by davidkpiano** [comment]
What is the "flux pattern" exactly? This is influenced by the actor model, where effects can be represented by "entities" and better managed that way.

We don't want to dispatch a special cleanup event because the logic for cleaning up needs to be handled in the reducer, and this is redundant:

```js
if (effect.type === SPECIAL_CLEANUP_EVENT) {
  // special logic
  if (shouldCleanupEffect(/* ... */)) {
    state.effect.stop();
  }
}
```

**Comment by Ephem** [comment]
Thanks for this library and opening this issue to discuss! I'm by no means an expert and I'll also just be thinking out loud here.

I think introducing effect cleanup is hard, not specifically because the cleanup itself is hard to implement correctly (which I also think it is), but also because thinking about these things exposes a few mismatches with the effect model, where I think it is very easy to create footguns for users when it comes to async effects.

The example you posted is a start, but some questions immediately spring to mind:

* Is canceling a side effect not in itself a side effect? Is it safe to run that within the reducer? Do we need to somehow trigger the cancelling of the effect in the actual effect cleanup behind the scenes to be Concurrent Mode safe?
* Is it up to the consumer of this library to dispatch `CANCEL` when a component unmounts? Would it be possible to do automatic effect cleanup in that case?

What is trickier though is how to handle race conditions.

* Is it up to the consumer to call `CANCEL` on an old fetch before doing a new one? If not, how do you handle that in this paradigm? With `useEffect` you often keep track of if the effect is stale or not, what is the equivalent here? Can we make something better?

I don't have any answers. I know @dai-shi implemented something like this using `AbortSignal` in [user-reducer-async abort examples](https://github.com/dai-shi/use-reducer-async/blob/master/examples/04_abort/src/) but I have no idea if it works as intended in all cases. Also, while nicer than juggling effects manually, any solution where you have to check for staleness yourself in userland is a bit cumbersome. I have no idea how to get around that though.

I'm not sure how to even approach this problem in a structured way to be honest. Maybe by collecting pseudo test-cases or requirements?

**Comment by Ephem** [comment]
I have been playing with the idea that it might be possible to use async generators for this. Instead of the user managing the staleness explicitly, they yield the effects they want and it's up to the library to only execute the ones that have not become stale.

Even ignoring async generators aren't exactly the most well known thing and a bit scary/not very ergonomic to many I have _no_ idea for how to align that with the React model though.. Just a loose though.

**Comment by Ephem** [comment]
I dug around some more and noticed your dog fetcher demo has a bug related to this. You can see it more clearly if you make the `setTimeout` delay random in `fetchRandomDog` and do some logging. Then click back and forth between Fetch and Cancel. You'll end up with a race condition where during the `loading`-state, an earlier fetch can resolve instead of the one you actually triggered.

**Comment by davidkpiano** [comment]
@Ephem That would be solved with this issue.

**Comment by Ephem** [comment]
Yup! That's why I didn't open a new issue, I just added it for context as a hands on problem. 😄

**Comment by davidkpiano** [comment]
Just added PR #8 to address this. TL;DR:

- `exec(effect)` - starts an effect
- `const entity = exec(effect)` - now you have a "reference" to that effect (its _entity_)
- `exec.stop(entity)` - disposes the effect represented by that _entity_
- Component unmount will dispose all running effects.
